dist: bionic

language: rust
rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --workspace
